"""remove image field

Revision ID: 021248122d27
Revises: e30fb4a7aa7e
Create Date: 2022-10-17 18:59:31.514533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021248122d27'
down_revision = 'e30fb4a7aa7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', sa.BLOB(), nullable=False))
    # ### end Alembic commands ###
