"""Product update optional values

Revision ID: 20d594f43bd8
Revises: 
Create Date: 2022-10-31 06:47:30.230348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20d594f43bd8'
down_revision = 'acc9350e8884'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'image',
                    existing_type=mysql.LONGBLOB(),
                    nullable=True)
    op.alter_column('product', 'description',
                    existing_type=mysql.VARCHAR(length=256),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'description',
                    existing_type=mysql.VARCHAR(length=256),
                    nullable=False)
    op.alter_column('product', 'image',
                    existing_type=mysql.LONGBLOB(),
                    nullable=False)
    # ### end Alembic commands ###
