"""init migration

Revision ID: 21bd31ff326a
Revises: 
Create Date: 2022-10-15 08:17:07.571741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21bd31ff326a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_type',
    sa.Column('id_product_type', sa.String(length=4), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id_product_type')
    )
    op.create_table('user',
    sa.Column('id_user', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('hashed_password', sa.String(length=60), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('business',
    sa.Column('id_business', sa.String(length=4), nullable=False),
    sa.Column('id_user', sa.String(length=4), nullable=True),
    sa.Column('name_business', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=70), nullable=False),
    sa.Column('image_logo', sa.BLOB(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_business')
    )
    op.create_table('product',
    sa.Column('id_product', sa.String(length=4), nullable=False),
    sa.Column('id_product_type', sa.String(length=4), nullable=True),
    sa.Column('id_business', sa.String(length=4), nullable=True),
    sa.Column('name_product', sa.String(length=100), nullable=False),
    sa.Column('price', sa.FLOAT(precision=10.2), nullable=False),
    sa.Column('image_product', sa.BLOB(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('final_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_business'], ['business.id_business'], ),
    sa.ForeignKeyConstraint(['id_product_type'], ['product_type.id_product_type'], ),
    sa.PrimaryKeyConstraint('id_product')
    )
    op.create_table('discount',
    sa.Column('id_discount', sa.String(length=4), nullable=False),
    sa.Column('id_product', sa.String(length=4), nullable=True),
    sa.Column('discount_ini', sa.DateTime(), nullable=False),
    sa.Column('discount_end', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_product'], ['product.id_product'], ),
    sa.PrimaryKeyConstraint('id_discount')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discount')
    op.drop_table('product')
    op.drop_table('business')
    op.drop_table('user')
    op.drop_table('product_type')
    # ### end Alembic commands ###
