"""add a new field to busines

Revision ID: 26499508eb43
Revises: f6b9bed138a1
Create Date: 2022-10-16 20:02:42.613296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26499508eb43'
down_revision = 'f6b9bed138a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('logo', sa.LargeBinary(length=4294967295), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'logo')
    # ### end Alembic commands ###
