"""change-table

Revision ID: 442753fd4f78
Revises: 1f04e5190919
Create Date: 2022-10-15 20:54:02.379866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442753fd4f78'
down_revision = '1f04e5190919'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('image_logo', sa.LargeBinary(length=4294967295), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'image_logo')
    # ### end Alembic commands ###
