"""modify product model

Revision ID: 640b3ebfe1a0
Revises: e03e0ce15752
Create Date: 2022-10-17 20:26:13.909291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640b3ebfe1a0'
down_revision = 'e03e0ce15752'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'amount')
    # ### end Alembic commands ###
