"""change table

Revision ID: 776e2d86a22f
Revises: 21bd31ff326a
Create Date: 2022-10-15 20:35:22.099749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776e2d86a22f'
down_revision = '21bd31ff326a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
