"""add a new field to business

Revision ID: f6b9bed138a1
Revises: fb46d3b7b4b4
Create Date: 2022-10-16 19:53:07.012999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b9bed138a1'
down_revision = 'fb46d3b7b4b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
