"""we add a new field to business

Revision ID: fb46d3b7b4b4
Revises: 1f0352ca0cd1
Create Date: 2022-10-16 19:49:59.819665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb46d3b7b4b4'
down_revision = '1f0352ca0cd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
