"""the product table NAME was modified

Revision ID: 0b16c2a94e12
Revises: 3a1210c4e85f
Create Date: 2022-11-14 17:19:38.096891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b16c2a94e12'
down_revision = '3a1210c4e85f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
