"""modified product table and business table

Revision ID: 6e5d9127ca6e
Revises: 0b16c2a94e12
Create Date: 2022-11-15 13:30:17.063845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5d9127ca6e'
down_revision = '0b16c2a94e12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
