"""added favorites table

Revision ID: c1cc9ca9dc9c
Revises: 9ad23e5a4f94
Create Date: 2022-11-24 16:12:10.756628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1cc9ca9dc9c'
down_revision = '9ad23e5a4f94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
